### ISSUE TITLE
Error on resolution request using an embedded model

### ISSUE THREAD

**Issue by benoitguigal** [zentity-io/zentity#10]
Whenever I try to perform a resolution request with an embedded entity model, I get a `validation_exception`, `You must specify either an entity type or an entity model`. The structure of my request follows the pattern described in the doc:
```
POST _zentity/resolution 
{
  "attributes": {...},
  "model": {...}
}
```

**Comment by davemoore-** [comment]
I've resolve this in b45b24a463836f88213984cc1538e29a1e2e1cbc which is included in the 1.3.1 release. Thanks for your contribution.
