### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by JinalParmar26** [zentity-io/zentity#103]
### Environment
- zentity version:  1.8.2
- Elasticsearch version: 7.15.1

### Describe the bug
I installed zentitty successfully on my windows machine.
While runing http://localhost:9200/_zentity ti thorws below error:
{"error":{"root_cause":[{"type":"invalid_index_name_exception","reason":"Invalid index name [_zentity], must not start with '_'.","index_uuid":"_na_","index":"_zentity"}],"type":"invalid_index_name_exception","reason":"Invalid index name [_zentity], must not start with '_'.","index_uuid":"_na_","index":"_zentity"},"status":400}

### Expected behavior

Zentity should run as expected after installation.

**Comment by austince** [comment]
Hmm, maybe there was some breaking change in elasticsearch, looks like 1.8.2 is only tested against 7.16.x and 7.17.x. Can you try to reproduce on one of those versions?

**Comment by davemoore-** [comment]
@JinalParmar26 I'm unable to reproduce this issue. I've installed zentity 1.8.2 on elasticsearch 7.15.1, and visiting http://localhost:9200/_zentity gives me the expected welcome message:

```json
{
  "name" : "zentity",
  "description" : "Entity resolution for Elasticsearch.",
  "website" : "https://zentity.io",
  "version" : {
    "zentity" : "1.8.2",
    "elasticsearch" : "7.15.1"
  }
}
```
