### ISSUE TITLE
Support for ElasticSearch 8.X

### ISSUE THREAD

**Issue by prabhushan** [zentity-io/zentity#108]
Hi,

We want Zentity to support latest Elastic Search version 8.x. Is there any roadmap for the same?

**Comment by prabhushan** [comment]
Hi.. any update on this request?

**Comment by szeitlin** [comment]
+1 and we might be able to help :)

**Comment by freemansoft** [comment]
+1

**Comment by MKRNaqeebi** [comment]
+1

**Comment by MKRNaqeebi** [comment]
+1

**Comment by prabhushan** [comment]
Any update on this?

**Comment by rajwilkhu** [comment]
+1

**Comment by rajwilkhu** [comment]
Is zentity.io being maintained? The last commit seems to have been made more than a year ago.

**Comment by prabhushan** [comment]
Hmmm.. I dont think so .

**Comment by cdgipson** [comment]
+1
I would love to see zentity.io support the latest version of ES.  My company has been using this tool with great success.

**Comment by davemoore-** [comment]
Hey everybody 👋🏻 I've released [zentity-1.8.3](https://zentity.io/releases/#zentity-1.8.3) which supports Elasticsearch 8.13.

My apologies for the lengthy delay. I've been on hiatus for a couple years to focus on my life and wellbeing. I'm happy to say that things are going well. I'm ready to maintain this project again.

**Comment by davemoore-** [comment]
@cdgipson @szeitlin If you're still interested in contributing, I'd be happy to talk more (see also this [discussion thread](https://github.com/zentity-io/zentity/discussions/61)). It'd be great to have more maintainers than just myself so that the project continues to progress in the event of my absence.
