### ISSUE TITLE
support recent patch versions for ES 7.17.x

### ISSUE THREAD

**Issue by rayzhangcl** [zentity-io/zentity#111]
Looks like the latest version has to match the ES patch version exactly. Any plan to support the most recent ES patch version?

`#7 10.81 Exception in thread "main" java.lang.IllegalArgumentException: Plugin [zentity] was built for Elasticsearch version 7.17.0 but version 7.17.5 is running`

**Comment by davemoore-** [comment]
I've released [zentity-1.8.3](https://zentity.io/releases/#zentity-1.8.3) which supports Elasticsearch 8.13. However, I won't be able to backport this to earlier versions of Elasticsearch due to its compatibility with the Elasticsearch Java API.
