### ISSUE TITLE
Get this error when try to install with elastic version 6.5

### ISSUE THREAD

**Issue by ravi-kothari** [zentity-io/zentity#12]
This plugin was built with an older plugin structure. Contact the plugin author to remove the intermediate "elasticsearch" directory within the plugin zip.

**Comment by davemoore-** [comment]
@ravi-kothari I need to update the plugin to support the latest versions of Elasticsearch. I'm going to work on that in the near future. Apologies for the delay, my attention has been towards my work lately.
