### ISSUE TITLE
Resolve nested objects in Zentity

### ISSUE THREAD

**Issue by prabhushan** [zentity-io/zentity#15]
We are using Zentity 6.2.4. We have processed atleast 30 million records for entity resolution and we are happy with the performance of the Zentity. As of now our records had linear data, but we got a new requirement to store array of objects.

For ex – License information stored as array.

`{
  "firstName":"John",
  "lastName":"Doe",
  "license" : [
    {
      "number" : "123"
    },
    {
      "number" : "456"
    }
  ]
}`

We would like to use Zentity to resolve this record with license number as well. But I am able to do it. I have given the index and other details for your assistance.
**Index Mapping**
http://ELKHOST/my_index
`{
  "mappings": {
    "_doc": {
      "properties": {
        "firstName": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "lastName": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "license": {
          "type": "nested",
          "properties": {
            "number": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            }
          }
        }
      }
    }
  }
}`

**Insert the first document**

POST http://ELKHOST/my_index/_doc/1

`{
  "firstName":"John",
  "lastName":"Doe",
  "license" : [
    {
      "number" : "123"
    },
    {
      "number" : "456"
    }
  ]
}`

**Zentity Model**
http://ELK HOST/_zentity/models/my_index
`{
  "attributes": {
    "firstName": {
      "type": "string"
    },
    "lastName": {
      "type": "string"
    },
    "licenseNumber": {
      "type": "string"
    }
  },
  "resolvers": {
    "name": {
      "attributes": [
        "lastName",
        "firstName"
      ]
    },
    "license": {
      "attributes": [
        "licenseNumber"
      ]
    }
  },
  "matchers": {
    "exact": {
      "clause": {
        "term": {
          "{{ field }}": "{{ value }}"
        }
      }
    },
    "fuzzy": {
      "clause": {
        "match": {
          "{{ field }}": {
            "query": "{{ value }}",
            "fuzziness": "auto",
            "operator": "AND"
          }
        }
      }
    }
  },
  "indices": {
    "my_index": {
      "fields": {
        "firstName": {
          "attribute": "firstName",
          "matcher": "fuzzy"
        },
        "lastName": {
          "attribute": "lastName",
          "matcher": "fuzzy"
        },
        "license.number": {
          "attribute": "licenseNumber",
          "matcher": "exact"
        }
      }
    }
  }
}`
Resolve the document using the below model
http://ELKHOST/_zentity/resolution/my_index
`{
  "attributes": {
    "lastName": [
      "Doe"
    ],
    "firstName":["John"]
  },
  "scope": {
  "include": {
    "indices": [
      "my_index"
    ],
    "resolvers": [
      "name"
    ]
  }
  }
}`

**I get the following error**
`{
    "error": {
        "root_cause": [
            {
                "type": "validation_exception",
                "reason": "Expected 'string' attribute data type."
            }
        ],
        "type": "validation_exception",
        "reason": "Expected 'string' attribute data type."
    },
    "status": 400
}`

But I see it when i bypass Zentity and query elastic search directly, it works fine.
http://ELKHOST/my_index/_search
`{
  "query": {
    "nested": {
      "path": "license",
      "query": {
        "bool": {
          "must": [
            { "match": { "license.number": "456" }}
          ]
        }
      }
    }
  }
}`

**Comment by davemoore-** [comment]
@prabhushan

It appears that you associated your `"exact"` matcher with your `"license.number"` field, which is a full-text value, but your `"exact"` matcher expects a keyword value, which would be `"license.number.keyword"`.

Here's where you can apply that change:

```javascript
{
  
  ...
  
  "indices": {
    "my_index": {
      "fields": {
        
        ...
        
        "license.number.keyword": {
          "attribute": "licenseNumber",
          "matcher": "exact"
        }
      }
    }
  }
}
```

Additionally, because `"license.number.keyword"` is part of a nested object, your matcher for that field needs to use the [`"nested"`](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-nested-query.html) query syntax. This only affects your `"license"` resolver. If you intend to submit resolution requests based on `"license"`, you should use the following matcher and index field configuration:

Here's where you can apply that change:

```javascript
{
  
  ...
  
  "matchers": {
    
    ...
    
    "exact_license_nested": {
      "clause": {
        "nested": {
          "path": "license",
          "query": {
            "term": {
              "{{ field }}": "{{ value }}"
            }
          }
        }
      }
    },
    
    ...
  }
  
  "indices": {
    "my_index": {
      "fields": {
        
        ...
        
        "license.number.keyword": {
          "attribute": "licenseNumber",
          "matcher": "exact_license_nested"
        }
      }
    }
  }
}
```

Here is the entire updated entity model:

```javascript
{
  "attributes": {
    "firstName": {
      "type": "string"
    },
    "lastName": {
      "type": "string"
    },
    "licenseNumber": {
      "type": "string"
    }
  },
  "resolvers": {
    "name": {
      "attributes": ["lastName", "firstName"]
    },
    "license": {
      "attributes": ["licenseNumber"]
    }
  },
  "matchers": {
    "exact": {
      "clause": {
        "term": {
          "{{ field }}": "{{ value }}"
        }
      }
    },
    "exact_license_nested": {
      "clause": {
        "nested": {
          "path": "license",
          "query": {
            "term": {
              "{{ field }}": "{{ value }}"
            }
          }
        }
      }
    },
    "fuzzy": {
      "clause": {
        "match": {
          "{{ field }}": {
            "query": "{{ value }}",
            "fuzziness": "auto",
            "operator": "AND"
          }
        }
      }
    }
  },
  "indices": {
    "my_index": {
      "fields": {
        "firstName": {
          "attribute": "firstName",
          "matcher": "fuzzy"
        },
        "lastName": {
          "attribute": "lastName",
          "matcher": "fuzzy"
        },
        "license.number.keyword": {
          "attribute": "licenseNumber",
          "matcher": "exact_license_nested"
        }
      }
    }
  }
}
```

The following resolution requests will now return your example document:

```javascript
POST _zentity/resolution/my_index
{
  "attributes": {
    "lastName": ["Doe"],
    "firstName": ["John"]
  },
  "scope": {
    "include": {
      "indices": ["my_index"],
      "resolvers": ["name"]
    }
  }
}
```

```javascript
POST _zentity/resolution/my_index
{
  "attributes": {
    "licenseNumber": ["123"]
  },
  "scope": {
    "include": {
      "indices": ["my_index"],
      "resolvers": ["license"]
    }
  }
}
```

As you continue to add fields to your nested `"license"` object, you can reuse the `"exact_license_nested"` matcher to perform exact matching on any of those fields. If you want to perform other kinds of matching on those fields, you'll need to create another matcher that uses the nested query syntax.

**Comment by prabhushan** [comment]
Thank you @davemoore- it worked perfectly.

**Comment by ml-alchimist** [comment]
Hello @prabhushan  can you share with me insight about zentity performance in your use case ? Please
