### ISSUE TITLE
Question: Debugging instructions

### ISSUE THREAD

**Issue by cosminonea** [zentity-io/zentity#34]
Hi,

I am trying to run the integration tests but get `Integration tests are skipped: got: "Connection refused", expected: not a string containing "Connection refused"` from the `io.zentity.resolution.AbstractITCase.startRestClient()`method because it can't connect to elasticsearch. Is there another step I am missing?

I am using Intellij but I am not a Java developer.

**Comment by davemoore-** [comment]
@cosminonea Sorry I didn't get to your question sooner. I'll close this issue because the test methods have changed entirely, so any answer I give will be obsolete.
