### ISSUE TITLE
Does zentity support multi_match query

### ISSUE THREAD

**Issue by johnhshi** [zentity-io/zentity#42]
This is the query I am looking for,
POST _zentity/resolution/zentity_tutorial_1_person?pretty&_source=false
{
  "attributes": {
    "first_name": [ "Allie" ],
    "last_name": [ "Jones" ]
  }
}

but it returns error:
{
  "took": 2,
  "error": {
    "by": "elasticsearch",
    "type": "org.elasticsearch.common.ParsingException",
    "reason": "[multi_match] query does not support [first_name]",
    "stack_trace": "ParsingException[[multi_match] query does not support [first_name]]

The entity model is defined here.
PUT _zentity/models/zentity_tutorial_1_person
{
  "attributes": {
    "first_name": {
      "type": "string"
    },
    "last_name": {
      "type": "string"
    }
  },
  "resolvers": {
    "name_only": {
      "attributes": [ "first_name", "last_name" ]
    }
  },
  "matchers": {
    "simple": {
      "clause": {
        "match": {
          "{{ field }}": "{{ value }}"
        }
      }
    },
    "multi_match": {
      "clause": {
        "multi_match": {
          "{{ field }}": "{{ value }}",
          "type":       "cross_fields",
          "fields":     [ "firs_tname", "last_name" ],
          "operator":   "and"
        }
      }
    }
  },
  "indices": {
    "zentity_tutorial_1_exact_name_matching": {
      "fields": {
        "first_name": {
          "attribute": "first_name",
          "matcher": "multi_match"
        },
        "last_name": {
          "attribute": "last_name",
          "matcher": "multi_match"
        }
      }
    }
  }
}

**Comment by davemoore-** [comment]
@johnhshi 

Your `multi_match` clause doesn't meet the syntax requirements of Elasticsearch. Elasticsearch requires `{{ value }}` to be in a field called `"query"` ([example](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html#type-cross-fields)).

Here's the corrected syntax:

```javascript
{
  "multi_match": {
    "query": "{{ value }}",
    "type": "cross_fields",
    "fields": ["first_name", "last_name"],
    "operator": "and"
  }
}
```

In your model, using the corrected clause syntax above, zentity would submit a query with two clauses: a `multi_match` on the value "Allie" on the fields `"first_name"` and `"last_name"`, and a `multi_match` clause on the value "Jones" on the fields `"first_name"` and `"last_name"`, where both `multi_match` clauses must evaluate to `true`. I believe that may produce the effect you're looking for.

You might notice that this is different than the example in the link above, which puts the values of `"first_name"` and `"last_name"` into a single `"query"` field. zentity doesn't support bringing multiple instances of `{{ field }}` or `{{ value }}` into a single matcher clause. Instead zentity combines clauses, each with a single `{{ field }}` and `{{ value }}`, under a `"must"` clause.
