### ISSUE TITLE
Proposal: Move CI from Travis to GitHub Actions

### ISSUE THREAD

**Issue by austince** [zentity-io/zentity#54]
## Overview

With [Travis CI's new pricing model](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing), Zentity is going to be transitioned to a new plan with limited free use. From their announcement:

> [we'll be moved to the] trial (free) plan with a 10K credit allotment (which allows around 1000 minutes in a Linux environment).
> When your credit allotment runs out - we’d love for you to consider which of our plans will meet your needs.
> We will be offering an allotment of OSS minutes that will be reviewed and allocated on a case by case basis. 

Given that, [GitHub Actions ](https://github.com/features/actions) makes a nice alternative for a few reasons:
* Completely free for all OSS projects
* Much faster build starts than Travis, which frequently has 
* Easier for contributors on GitHub to fork and automatically have CI setup
  * Could potentially make it easy for Zentity members to approve running PRs from untrusted public forks via PR comments, labels, CODEOWNER approval, etc.

GH Actions do have some areas that aren't so nice:
* More customizable, and therefore more complicated to set up, than Travis
  * ex: no simple [`deploy` configuration](https://github.com/zentity-io/zentity/blob/40b8661563413a2da7223f9059cfbc33e4102775/.travis.yml#L20-L27)
* Each action that is used in a CI workflow is like a new dependency, and come with similar drawbacks  

## Migration Details

I think we can both test and release in one [workflow](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/introduction-to-github-actions#workflows), but I'll start with tests.

### Tests

In one [job](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/introduction-to-github-actions#jobs):
* Run on every commit pushed to any branch
  * see [`on.push`](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onevent_nametypes) 
* Run on [ubuntu-20.04](https://github.com/actions/virtual-environments#available-environments)
* Use `matrix` to test multiple different versions of Elasticsearch (almost the same as Travis's `matrix`) 
  * Eventually could run on Windows + macOS too?
* steps:
  * Check out the code via [actions/checkout](https://github.com/actions/checkout)
  * Setup Java 11 via [actions/setup-java](https://github.com/actions/setup-java)
  * Run unit and integration via directly running the `mvn` cli (same as [currently in Travis](https://github.com/zentity-io/zentity/blob/40b8661563413a2da7223f9059cfbc33e4102775/.travis.yml#L18))
    * see: https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-java-with-maven 
  * Cache Maven packages after each run via [actions/cache](https://github.com/actions/cache) and a hash of the os + `pom.xml` file
    * see: https://docs.github.com/en/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows 

### Releases

This is where the workflow would be quite different than Travis.

In a second job:
* Only run on tags
  * This could be the current format, or could be extended to allow for easy Release Candidate creation in the format  `*.*.*-rc*`
  * see [`on.push.tags`](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags)
* Create a GitHub release with the tag via [actions/create-release](https://github.com/actions/create-release)
* Upload artifacts for each of the matrix ES versions and the Zentity tag to the created release via [actions/upload-release-asset](https://github.com/actions/upload-release-asset)

Optionally, we could also automatically create a changelog for the release body (or to add to a separate file) via something like [mikepenz/release-changelog-builder-action](https://github.com/actions/mikepenz/release-changelog-builder-action). 

## Conclusion

How does this compare with your current process for releasing Zentity?

Please let me know what you think! I'm happy to adjust/find more resources on/ talk about anything in here!

**Comment by davemoore-** [comment]
@austince I love it. I've pushed PR #69 which implements GitHub Actions and retires Travis CI. Thanks for your guidance here.

Travis CI is effectively unusable now that jobs queue for many hours and cancel unpredictably. GitHub Actions (as of PR #69) has been excellent. I look forward to using this ASAP.

**Comment by davemoore-** [comment]
Merged into master
