### ISSUE TITLE
Release Plan 1.8.0

### ISSUE THREAD

**Issue by davemoore-** [zentity-io/zentity#78]
# Release Plan: 1.8.0

## Changes

- [x] Feature: Bulk resolution (Issue: #50, PR: #79)
- [x] Feature: Bulk model management (Issue: #57)

## Release

- [x] Create branch `1.8.0` from `main` branch
- [x] Update `zentity.version` in pom.xml and version numbers in README.md
- [x] Tag as `zentity-1.8.0` and push to build and deploy its release artifacts
- [x] Verify successful deployment

## Post-release

- [x] Update zentity.io home
- [x] Update zentity.io releases
- [x] Update zentity.io documentation

**Comment by davemoore-** [comment]
Released! 🚀

Thank you @austince for your excellent contributions to this release.

**Comment by austince** [comment]
Great work Dave, was great collaborating on this + happy to see it out in the world!
